### ISSUE TITLE
Only one Tomcat server is provisioned as opposed to the Architecture Center diagram

### ISSUE THREAD

**Issue by jngithub1** [oracle-quickstart/oci-arch-tomcat-autonomous#1]
Thank you for the nice new demo. However, I noticed that only one Tomcat server is provisioned as opposed to the Architecture Center diagram. Hence demoing with a load balancer does not work that well. It takes a little work to make it provision a second Tomcat server. Not everyone may be able to do this quickly. It took me some time.

**Comment by oegentil** [comment]
Thanks for the feedback. I'll update that soon. I'll keep you posted.

**Comment by jngithub1** [comment]
It wasn't that hard to fix it, I could upload my added/modified files if you want. I also had an issue with the file() clause used for the ssh private key

**Comment by oegentil** [comment]
@jngithub1,
I had fixed by the time I read your offer. Thanks anyways =)
What was the issue you had with the file() and the private key?

**Comment by jngithub1** [comment]
About the file() clause in appserver-config.tf used for the ssh private key in remote-exec: on MacOS that didn't work with file() so I replaced it with private_key = var.ssh_private_key and that worked fine
