### ISSUE TITLE
Please either update your repo either retire it on profit of Live Labs

### ISSUE THREAD

**Issue by eugsim1** [oracle-quickstart/oci-arch-tomcat-autonomous#7]
Hi
In this implementation several things are missing as par example the Autonomous database scripts, i m wondering how you are able to run the this without ANY DATABASE sql info, similar info is on LIVE LABs with the scripts , so could you either UPDATE the repo or RETIRE IT its referenced in the Reference Architecture but i dont catch why all the bits and bites are not HERE ?
If as its stated there is AN UPDATE THEN FORWARD to the correct location
thanks

**Comment by oegentil** [comment]
The idea of the reference architecture (and the repo) is to deploy a sample application (todo app). The TF scripts should cover everything, including the SQL commands to set up that. The user does not need to run anything besides terraform. For what the RA proposes, which scripts are missing?

The Tomcat LiveLabs takes advantage of that and on top of it, the lab does other activities. The lab's scripts are not part of the quick-start repo. The lab repo is [here](https://github.com/oracle/learning-library/tree/master/developer-library/tomcat-to-oci).

I hope that answers your question. If I understood it wrong please rephrase it and I'll try to answer that.

Take care,

**Comment by eugsim1** [comment]
Hi Thanks for the info , if on then next workshop i will through this code to the customer i dont think that they will appreciate. if the author believes that this code as its delivered describes a reference architecture compared to Live Labs then i missing a point and maybe i have to scrap my tf skills , and learn from this deliverables.
I m internal and you can ping me if you want more details.

**Comment by oegentil** [comment]
closing issue as no further feedback was provided. feel free to reopen or contact me.
